### ISSUE TITLE
Formatting issues in the code

### ISSUE THREAD

**Issue by cshlatz** [cshlatz/kazaam2D#12]
There are some strangely formatted files. I suspect they may be tabs that were autogenerated from monodevelop. Let's get that cleaned up a bit.

**Comment by cshlatz** [comment]
Console.WriteLines should be removed as well

**Comment by cshlatz** [comment]
The code also looks like shit

**Comment by Ichimonji10** [comment]
Are there tools that can auto-format code for you? Something like Rust's `rustfmt`, or Python's [black](https://pypi.org/project/black/).

**Comment by cshlatz** [comment]
> Are there tools that can auto-format code for you? I'm thinking of something like Rust's `rustfmt`, or Python's [black](https://pypi.org/project/black/).

There doesn't appear to be a good command line formatter for C#, but MonoDevelop should be able to do this.

**Comment by cshlatz** [comment]
All tab characters have been removed in various commits. Closing this but will fix any strangely formatted files as I come across them.
